name: Waka Readme

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL: false
          SHOW_TITLE: false
          TIME_RANGE: all_time
          SHOW_LINES_OF_CODE: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE_PER_REPO: false
          UPDATED_DATE_FORMAT: "%Y-%m-%d"
          
